Created Profile and Settings Page
cornell-dti/carriage-android pull request #6
Opened 2019-11-24 19:35 UTC by tyang98

### Summary 
This pull request creates the profile and settings page for the Rider app, as well as adds Google Authentication to retrieve information from user.

### Notes 

Need to fix the logout button, because it currently does not remove the user login from the app.

### Screenshots 
<img width="319" alt="Login" src="https://user-images.githubusercontent.com/17262023/69500188-f2eaa980-0ec6-11ea-8028-3a79adafb926.png">
<img width="319" alt="Profile" src="https://user-images.githubusercontent.com/17262023/69500191-fe3dd500-0ec6-11ea-9bea-27f1ff9a8db8.png">
<img width="320" alt="Settings" src="https://user-images.githubusercontent.com/17262023/69500196-05fd7980-0ec7-11ea-83b4-d101e759136a.png">

2019-11-24 20:02 UTC, SamChou19815 commented on Rider/app/src/main/java/com/dti/rider/ProfileActivity.kt
> +    lateinit var email : TextView
Do these fields need to be public?

2019-11-24 20:02 UTC, SamChou19815 requested changes
Problems

2019-11-25 16:36 UTC, tyang98 commented on Rider/app/src/main/java/com/dti/rider/ProfileActivity.kt
> +    lateinit var email : TextView
No they do not have to be.

2019-11-25 22:15 UTC, SamChou19815 commented
@tyang98 Could you deal with merge conflicts first?

2020-02-11 22:33 UTC, closed without merging